### ISSUE TITLE
Cron job interval in README doesn't match expression

### ISSUE THREAD

**Issue by michaelmior** [devrim/cloudflare-noip#1]
The cron expression in the README runs the script every 60 minutes, but the README text says it is every 5 minutes.

**Comment by sigio** [comment]
Yeah, that would have to be:
```
*/5 * * * * ...
```

**Comment by devrim** [comment]
thank you! and fixed.

**Comment by michaelmior** [comment]
@devrim I see that the README now says that another user "rightly" pointed out that one minute is more appropriate. Since it seems that you agree, then I wonder why not just change the cron expression to update every minute?

**Comment by devrim** [comment]
i wasn't sure about the cf api quotas, now i see it's 1200 per 5 minutes so i'll change it...
